### ISSUE TITLE
Version checking thinks "RELEASE" is not up-to-date

### ISSUE THREAD

**Issue by seancorfield** [Olical/depot#11]
This is kind of a follow on from #7 but for the checking side of Depot, rather than the updating side: the version checker reports that `"RELEASE"` is out of date compared to whatever the latest stable release actually is.

As noted in that other ticket, we only use `"RELEASE"` for dev/test tooling where we always want to ensure we're always on the most recent release, without needing any manual process to update dependencies.

**Comment by Olical** [comment]
Did this go away when you tried out one of the newer master commits for v2.0.0, out of interest?

**Comment by seancorfield** [comment]
Hard to tell -- v2 doesn't work with our work repo setup!

**Comment by seancorfield** [comment]
I just noticed that `:override-deps` and `:extra-deps` are being included in the latest commit (not sure if the user-level deps is being read tho'?), so I've pulled the latest Depot (and removed my workarounds first!) and I'm re-running my test to see if the overrides work now.

If that works, I'll go over our dev tooling and see if we still use RELEASE and then re-check this.

**Comment by seancorfield** [comment]
No, it does not work yet. It is not paying any attention to the user-level `deps.edn` file, as far as I can tell.

**Comment by Olical** [comment]
Sorry I completely forgot about this issue and the changes @lverns submitted, I need to get this across the line really so the master branch has a released tag. Wondering what needs to be done to finish it off, guessing it's still an issue?

**Comment by seancorfield** [comment]
It's no longer an issue for me -- I no longer use Depot.

**Comment by Olical** [comment]
Completely understandable! :smile: this tool definitely needs some love, just got to find the time and energy to do it. I'll leave this open as a note for now, would be worth bearing in mind with any changes or rewrites.

**Comment by seancorfield** [comment]
In case you're curious, I ended up doing it via a fairly simple shell script that ran `clojure -Stree` on my code and edited the output into a new `deps.edn` in a temp folder with `"RELEASE"` in place of the actual versions, then ran `clojure -Stree` on that "project" and compared the output with the original deps tree (I can filter deps by depth so I can exclusive some or all transient deps).

**Comment by Olical** [comment]
Oooo I really like that! Thanks for the tip!
