### ISSUE TITLE
Does not look at extra-deps?

### ISSUE THREAD

**Issue by danieroux** [Olical/depot#2]
Invoking both of these deps.edn with `clojure -Adev:outdated -a outdated`:

This works as expected, and tells me cider-nrepl is old:

```
{:deps {cider/cider-nrepl {:mvn/version "0.13.0"}}

 :aliases {:outdated {:extra-deps {olical/depot {:mvn/version "1.0.1"}}
                      :main-opts  ["-m" "depot.outdated.main"]}

           :dev {:extra-deps {}}}}
```

This does not pick up that cider-nrepl is old, seems like :extra-deps are ignored?

```
{:deps {}

 :aliases {:outdated {:extra-deps {olical/depot {:mvn/version "1.0.1"}}
                      :main-opts  ["-m" "depot.outdated.main"]}

           :dev {:extra-deps {cider/cider-nrepl {:mvn/version "0.13.0"}}}}}
```

**Comment by Olical** [comment]
Hey! Would you be able to share what your `deps.edn` looks like and what `clojure` / `clj` command you were executing? `:extra-deps` should work totally fine.

**Comment by danieroux** [comment]
@Olical you responded faster than I could write the bug report ;-)

**Comment by Olical** [comment]
Haha, sorry about that! I'd just sat down with my laptop :laughing: I'll take a look, thanks a lot!

**Comment by Olical** [comment]
Ah, got it, it's just the way you're calling it, thankfully :smile: maybe it's a documentation issue though.

You need `clojure -Aoutdated -a dev`, where the `-A` causes depot to be executed and the `-a dev` tells depot what alias to check. You don't need the `dev` on the left hand side, but you can add it if you want to.

Depot reads and parses your `deps.edn` itself with it's own alias list, so you don't need depot installed in your local project to run it. You can install it via the `deps.edn` in your home folder and still execute it like the aforementioned command.

I hope this helps!

**Comment by danieroux** [comment]
Thank you!

**Comment by didibus** [comment]
There's not a way to have it check all aliases?

**Comment by aviflax** [comment]
This wasn’t clear to me either, so yeah maybe the docs could be checked.
