### ISSUE TITLE
--overrides only has effect when used with --update

### ISSUE THREAD

**Issue by lverns** [Olical/depot#22]
The title pretty much says it all. If I pass `--overrides --update`, the dependencies under `:override-deps` get updated, but if I pass `--overrides` without the update flag, it is as if I had not passed any flag.

Tested against 1.8.2

Related to #12 I suppose.

**Comment by Olical** [comment]
Thanks for reporting! This could probably be patched out but I'm definitely feeling a re-write or at least a huge refactor around the corner. It's probably the best way to address every open issue right now. Having two majorly different code paths is not great :grimacing:

**Comment by lverns** [comment]
@Olical After unification of the code paths, do we want to keep support for `--overrides` or do we want to drop it?

The same question applies for `--aliases`.

**Comment by Olical** [comment]
Honestly not sure, I feel pretty out of context. It might be worth rethinking it from a fresh point, not trying to hold onto ideas from the current incarnation. Then if something like overrides and aliases fall out of the new design (that can update in place or tell you what it would do) then great.

I can't offer much advice on it right now though I'm afraid, lots of life stuff going on and only really focussing on Conjure for open source right now.

**Comment by Olical** [comment]
I think you probably fixed this yourself, right?

**Comment by lverns** [comment]
@Olical Correct. 
As per the changelog, I actually dropped support for the flag completely and always check the `:override-deps` unless they're marked with the `:depot/ignore` metadata.

If we decide that we want to bring the flag back, it won't be hard, but since my complaint was about the consistency of the flag I'll close this.
