### ISSUE TITLE
depot considers versions that are only available in local repo

### ISSUE THREAD

**Issue by dchelimsky** [Olical/depot#33]
# Scenario

* my project depends on library xyz 1.0.0
* the most recent public release of xyz is 1.0.1
* my local maven repo has a more recent version of xyz, 1.0.2, that I built and installed locally

# Expected
* depot reports current 1.0.0 and newest 1.0.1 (the newest version available from remote repos)

# Actual
* depot reports current 1.0.0 and newest 1.0.2 (the version that only exists on my machine)

**Comment by puredanger** [comment]
I actually think the behavior is fine here (and probably a pain in the ass to make it not do this), but one way to do so would be to use `-Sdeps '{:mvn/local-repo "/tmp/m2"}'` to isolate yourself from the main local repo.

**Comment by dchelimsky** [comment]
@puredanger's comment resolves this for me, so closing.
