### ISSUE TITLE
depot adds :mvn/version to dep with :local/root

### ISSUE THREAD

**Issue by dchelimsky** [Olical/depot#34]
I ran depot with `--update` and it updated e.g.

```
{some/lib {:local/root "../some/lib"}}
```

to e.g.

```
{some/lib {:local/root "../some/lib" :mvn/version "1.2.3"}}
```

I think this should not be allowed, and depot should ignore deps declared with `:local/root`.

**Comment by lverns** [comment]
Yeah, definitely bad behavior. What version of depot was this?

**Comment by dchelimsky** [comment]
Welp, I thought it was 1.8.4 (current), but I just tried to validate that and now, of course, it's not happening. ¯\_(ツ)_/¯
