### ISSUE TITLE
Range Not Satisfiable (416) when running clj -Aoutdated

### ISSUE THREAD

**Issue by pragyanatvade** [Olical/depot#45]
My `deps.edn` has following snippet:

```
 :outdated {:extra-deps {olical/depot {:mvn/version "1.8.4"}}
                      :main-opts  ["-m" "depot.outdated.main"]}
```

But when I run `clj -Aoutdated` it exits with the following error

```
Error building classpath. Could not transfer artifact com.jcraft:jsch:jar:0.1.54 from/to central (https://repo1.maven.org/maven2/): Range Not Satisfiable (416)
```

Anyway to resolve this?

**Comment by pragyanatvade** [comment]
I resolved this issue by deleting the `~/.m2` directory and rerunning the command.

**Comment by Olical** [comment]
Glad you worked it out! I was just going to ask for more information to begin understanding it :sweat_smile:
