### ISSUE TITLE
Check default-deps in aliases

### ISSUE THREAD

**Issue by timothypratley** [Olical/depot#54]
Will you accept a minor patch to include `:default-deps` in the alias keys that get checked?

In aliases, dependencies can appear under `:extra-deps`, `:override-deps` and `:default-deps`.
Reference https://clojure.org/reference/deps_and_cli#_resolve_deps

The current behavior is that only `:extra-deps` and `override-deps` are checked.

**Comment by Olical** [comment]
Thanks for checking and yeah, I think that'll be fine :)

**Comment by timothypratley** [comment]
👍 Cool :)
I've tested the attached PR locally and it works :)

**Comment by timothypratley** [comment]
👍 Should be good to go now, it works for me locally

**Comment by Olical** [comment]
Published!

**Comment by timothypratley** [comment]
Thank you :)
